[package]

name = "tiny-asm"
version = "0.0.1"
authors = ["Markus Siemens <siemens1993@gmail.com>"]

[[bin]]
name = "tiny"
path = "src/main.rs"

[[bin]]
name = "rustiny"
path = "src/compiler/main.rs"


[profile.release]
opt-level = 3
lto = true

[dependencies]
ansi_term = "*"
docopt = "*"
docopt_macros = "*"
env_logger = "*"
lazy_static = "*"
log = "*"
rand = "*"
rustc-serialize = "*"